//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.CtDonHang = new HashSet<CtDonHang>();
        }
    
        public string soDH { get; set; }
        public string maKH { get; set; }
        public string taiKhoan { get; set; }
        public Nullable<System.DateTime> ngayDat { get; set; }
        public Nullable<bool> daKichHoat { get; set; }
        public Nullable<System.DateTime> ngayGH { get; set; }
        public string diaChiGH { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<CtDonHang> CtDonHang { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual TaiKhoan TaiKhoan1 { get; set; }
    }
}
