//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShopOnline_Demo : DbContext
    {
        public ShopOnline_Demo()
            : base("name=ShopOnline_Demo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BaiViet> BaiViet { get; set; }
        public DbSet<CtDonHang> CtDonHang { get; set; }
        public DbSet<DonHang> DonHang { get; set; }
        public DbSet<KhachHang> KhachHang { get; set; }
        public DbSet<LoaiSP> LoaiSP { get; set; }
        public DbSet<SanPham> SanPham { get; set; }
        public DbSet<TaiKhoan> TaiKhoan { get; set; }
    }
}
