//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public TaiKhoan()
        {
            this.BaiViet = new HashSet<BaiViet>();
            this.DonHang = new HashSet<DonHang>();
            this.SanPham = new HashSet<SanPham>();
        }
    
        public string taiKhoan1 { get; set; }
        public string matKhau { get; set; }
        public string hoDem { get; set; }
        public string tenTV { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public Nullable<bool> gioiTinh { get; set; }
        public string soDT { get; set; }
        public string email { get; set; }
        public string diaChi { get; set; }
        public Nullable<bool> trangThai { get; set; }
        public string ghiChu { get; set; }
    
        public virtual ICollection<BaiViet> BaiViet { get; set; }
        public virtual ICollection<DonHang> DonHang { get; set; }
        public virtual ICollection<SanPham> SanPham { get; set; }
    }
}
